name: System Information Check

# This allows you to run the job manually from the "Actions" tab
on: workflow_dispatch

jobs:
  first-job:
    # Fix: Ensure this is spelled 'ubuntu-latest'
    runs-on: ubuntu-latest

    steps:
       - name: github context object 
         run : echo "${{toJson(github)}}"
       - name: env context obj
         run : echo  "${{toJson(env)}}"
       - name: secrets 
         run: echo "${{toJson(secrets)}}"
       - name: runner     
         run : echo "${{toJson(runner)}}"
    
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: list Files
        run : ls -a 
        
      
      - uses: actions/checkout@v6
      - name: list files
        run: ls -a
       
      
