name: System Information Check

# This allows you to run the job manually from the "Actions" tab
on: workflow_dispatch

jobs:
  first-job:
    # Fix: Ensure this is spelled 'ubuntu-latest'
    runs-on: ubuntu-latest

    steps:
       - name: expression 
         run : ${{4 > 2}}
      

  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: list Files
        run : ls -a 
        
      
      - uses: actions/checkout@v6
      - name: list files
        run: ls -a
       
      
